apiVersion: v1
kind: Service
metadata:
  labels:
    app: pages
    tier: service
  name: pages
  namespace: dev-test
spec:
  ports:
  - port: 8080
{{- range .Values.serviceConf }}
{{ .name | indent 4 }}: {{ .value }}
{{- end }}
  selector:
    app: pages
    tier: service
  type: NodePort
