apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx4
spec:
  containers:
  - image: nginx
    name: nginx
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 20m
        memory: 40Mi
      requests:
        cpu: 10m
        memory: 20Mi

