apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-dev-test
  namespace: dev-test
spec:
  storageClassName: database
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
