apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deploy-nginx-recreate
  name: deploy-nginx-recreate
spec:
  replicas: 5
  selector:
    matchLabels:
      app: deploy-nginx
  strategy:
     type: Recreate
  template:
    metadata:
      labels:
        app: deploy-nginx
    spec:
      containers:
      - image: nginx:1.18
        name: nginx

