apiVersion: v1
kind: Pod
metadata:
  labels:
    name: nginx
    type: web-application
  name: nginx-with-service
spec:
  containers:
  - image: nginx
    name: nginx-with-service
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx
    type: web-application
  name: nginx-service
spec:
  type: ClusterIP
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 80
  selector:
    name: nginx
    type: web-application
