apiVersion: v1
kind: Pod
metadata:
  name: cm-secret-pod
spec:
  containers:
  - name: alpine
    image: alpine
    imagePullPolicy: IfNotPresent
    command: ["sh","-c","while true;do echo 'Db User is $(DB_USER) and password is $(DB_PASSWORD) at ';date;sleep 5;done"]
    envFrom:
    - configMapRef:
        name: dbuser
    - secretRef:
        name: dbpassword
