apiVersion: v1
kind: Pod
metadata:
  name: cm-secret-vol-pod
spec:
  volumes:
  - name: dbuser-volume
    configMap:
      name: dbuser
  - name: dbpassword-volume
    secret:
      secretName: dbpassword
  containers:
  - name: alpine
    image: alpine
    imagePullPolicy: IfNotPresent
    command: ["sh","-c",'while true; do echo "DB Username is ";cat /data/dbuser/DB_USER; echo " and DB Password is ";cat /data/dbpassword/DB_PASSWORD;echo -e " at  $(date) \n";sleep 5; done;']
    volumeMounts:
    - name: dbuser-volume
      mountPath: /data/dbuser
    - name: dbpassword-volume
      mountPath: /data/dbpassword
