apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: my-cron
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: my-cron
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - sh
            - -c
            - date
            image: alpine
            imagePullPolicy: IfNotPresent
            name: my-cron
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/4 * * * *'
status: {}
