apiVersion: batch/v1
kind: Job
metadata:
  name: my-print-job
spec:
  template:
    metadata:
    spec:
      containers:
      - command:
        - sh
        - -c
        - date
        image: alpine
        imagePullPolicy: IfNotPresent
        name: my-print-job
        resources: {}
      restartPolicy: Never
status: {}
