apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mypod
  name: time-mypod
spec:
  containers:
  - args:
    - sh
    - -c
    - sleep 2000
    image: alpine
    name: mypod
    securityContext:
      capabilities:
         add: ["SYS_TIME"]
