apiVersion: v1
kind: Pod
metadata:
  labels:
    app: microservice
    tier: database
    type: database
  name: mysql
spec:
  containers:
  - image: mysql:8.0
    imagePullPolicy: IfNotPresent
    name: mysql
    env:
      - name: "MYSQL_ROOT_PASSWORD"
        value: "root"