apiVersion: v1
kind: Pod
metadata:
  labels:
    app: microservice
    tier: backend
    type: cache
  name: redis
spec:
  containers:
  - image: redis
    imagePullPolicy: IfNotPresent
    name: redis
